version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    networks:
      - password-manager-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/userlist_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - password-manager-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=userlist_db
    ports:
      - "5432:5432"
    networks:
      - password-manager-network

networks:
  password-manager-network:
    driver: bridge
